name: test

on:
  push:
    branches: []
    tags: []
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go 1.23
      uses: actions/setup-go@v5
      with:
        go-version: stable
        cache: false

    - name: Test
      run: |
        echo "Testing..."
        go test ./...

